/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Booking;
import Controller.*;
import Model.Room;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Nhattruong
 */
public class BookingView extends javax.swing.JFrame {

    private JPanel contentPane;

    /**
     * Creates new form BookingView
     */
    public BookingView() {
        initComponents();
        frame = new JFrame("Booking Management");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public String getCusId() {
        return cusIdTF.getText();
    }
    
    public String getRoomId() {
        return roomIdTF.getText();
    }

    public String getBookingId() {
        return idTF.getText();
    }

    public String getCheckInDate() {
        Date selectedDate = ckinDateTF.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String formattedDate = dateFormat.format(selectedDate);
        return formattedDate;
    }
    
    public String getCheckOutDate() {
        Date selectedDate = ckoutDateTF.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String formattedDate = dateFormat.format(selectedDate);
        return formattedDate;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ckoutDateTF = new com.toedter.calendar.JDateChooser();
        logoutViewBtn = new javax.swing.JButton();
        billViewBtn = new javax.swing.JButton();
        serviceViewBtn = new javax.swing.JButton();
        customerViewBtn = new javax.swing.JButton();
        roomViewBtn = new javax.swing.JButton();
        bookingViewBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        delBookingBtn = new javax.swing.JButton();
        updBookingBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomsTable = new javax.swing.JTable();
        addBookingBtn = new javax.swing.JButton();
        ckinDateTF = new com.toedter.calendar.JDateChooser();
        cusIdTF = new javax.swing.JTextField();
        roomIdTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingsTB = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ckoutDateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 576, 235, 30));

        logoutViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/icon logout.png"))); // NOI18N
        logoutViewBtn.setBorder(null);
        logoutViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 4, -1, -1));

        billViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/icon bill.png"))); // NOI18N
        billViewBtn.setBorder(null);
        billViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(billViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 4, -1, -1));

        serviceViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/icon service.png"))); // NOI18N
        serviceViewBtn.setBorder(null);
        serviceViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(serviceViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 5, -1, -1));

        customerViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/icon customer.png"))); // NOI18N
        customerViewBtn.setBorder(null);
        customerViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 4, -1, -1));

        roomViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/icon room.png"))); // NOI18N
        roomViewBtn.setBorder(null);
        roomViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(roomViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 4, -1, -1));

        bookingViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/icon booking.png"))); // NOI18N
        bookingViewBtn.setBorder(null);
        getContentPane().add(bookingViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 4, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 693, -1, -1));
        getContentPane().add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 693, 100, -1));

        delBookingBtn.setBackground(new java.awt.Color(236, 108, 108));
        delBookingBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delBookingBtn.setText("Delete");
        delBookingBtn.setBorder(null);
        delBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBookingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(delBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 693, 75, 20));

        updBookingBtn.setBackground(new java.awt.Color(236, 200, 108));
        updBookingBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updBookingBtn.setText("Update");
        updBookingBtn.setBorder(null);
        updBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBookingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 662, 90, 20));

        RoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Room Name", "Type", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(RoomsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 490, 210));

        addBookingBtn.setBackground(new java.awt.Color(111, 236, 108));
        addBookingBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBookingBtn.setText("Add");
        addBookingBtn.setBorder(null);
        addBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 662, 70, 20));
        getContentPane().add(ckinDateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 490, 235, 30));

        cusIdTF.setBorder(null);
        getContentPane().add(cusIdTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 315, 235, 30));

        roomIdTF.setBorder(null);
        getContentPane().add(roomIdTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 400, 235, 30));

        bookingsTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Customer ID", "Room ID", "Booking date", "Check in date", "Check out date"
            }
        ));
        jScrollPane2.setViewportView(bookingsTB);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 507, 490, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/Booking.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String[][] dataTransfer(ArrayList<Booking> bookings){
        int i =0 ;
        String data[][] = new String[bookings.size()][6];
        for(Booking booking : bookings){
            data[i][0] = String.valueOf(booking.getBookingId());
            data[i][1] = String.valueOf(booking.getCusId());
            data[i][2] = String.valueOf(booking.getRoomId());
            data[i][3] = booking.getBookingDate();
            data[i][4] = booking.getCheckInDate();
            data[i][5] = booking.getCheckOutDate();
            i++;
        }
        return data;
    }
    
    public void displayBookings(ArrayList<Booking> bookings, ArrayList<Room> rooms) {
        String[][] data1 = dataTransfer(bookings);
        String[] column1 = {"Booking ID", "Customer ID", "Room ID", "Booking date", "Check in date", "Check out date"};
        DefaultTableModel dataModel1 = new DefaultTableModel(data1, column1);
        bookingsTB.setModel(dataModel1);
        
        String[][] data2 = dataTransferRoom(rooms);
        String[] column2 = {"Room ID", "Room Name", "Type", "Price", "Status", "HT/HS ID"};
        DefaultTableModel dataModel2 = new DefaultTableModel(data2, column2);
        RoomsTable.setModel(dataModel2);
        
        frame.setVisible(true);
    }

    public String[][] dataTransferRoom(ArrayList<Room> rooms){
        int i =0 ;
        String data[][] = new String[rooms.size()][6];
        for(Room room : rooms){
            data[i][0] = String.valueOf(room.getRoomId());
            data[i][1] = room.getRoomName();
            data[i][2] = room.getRoomType();
            data[i][3] = String.valueOf(room.getRoomRates());
            data[i][4] = String.valueOf(room.isRoomStatus());
            data[i][5] = String.valueOf(room.getHtId());
            i++;
        }
        return data;
    }
    
    public void addBookingBtnListener(ActionListener listener) {
        addBookingBtn.addActionListener(listener);
    }
    public void updBookingBtnListener(ActionListener listener) {
        updBookingBtn.addActionListener(listener);
    }
    public void delBookingBtnListener(ActionListener listener) {
        delBookingBtn.addActionListener(listener);
    }
    public void customerViewBtnListener(ActionListener listener) {
        customerViewBtn.addActionListener(listener);
    }
    public void roomViewBtnListener(ActionListener listener) {
        roomViewBtn.addActionListener(listener);
    }
    public void serviceViewBtnListener(ActionListener listener) {
        serviceViewBtn.addActionListener(listener);
    }
    public void billViewBtnListener(ActionListener listener) {
       billViewBtn.addActionListener(listener);
    }
    public void logoutViewBtnListener(ActionListener listener) {
        logoutViewBtn.addActionListener(listener);
    }
    
    private void addBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingBtnActionPerformed
        if (addBookingBtnListener != null) {
            addBookingBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_addBookingBtnActionPerformed

    private void roomViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomViewBtnActionPerformed
        if (roomViewBtnListener != null) {
            roomViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_roomViewBtnActionPerformed

    private void customerViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerViewBtnActionPerformed
        if (customerViewBtnListener != null) {
            customerViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_customerViewBtnActionPerformed

    private void serviceViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceViewBtnActionPerformed
        if (serviceViewBtnListener != null) {
            serviceViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_serviceViewBtnActionPerformed

    private void billViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billViewBtnActionPerformed
        if (billViewBtnListener != null) {
            billViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_billViewBtnActionPerformed

    private void logoutViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutViewBtnActionPerformed
        if (logoutViewBtnListener != null) {
            logoutViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_logoutViewBtnActionPerformed

    private void updBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBookingBtnActionPerformed
        if (updBookingBtnListener != null) {
            updBookingBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_updBookingBtnActionPerformed

    private void delBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBookingBtnActionPerformed
        if (delBookingBtnListener != null) {
            delBookingBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_delBookingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingView().setVisible(true);
            }
        });
    }

    private JFrame frame;
    private ActionListener addBookingBtnListener;
    private ActionListener delBookingBtnListener;
    private ActionListener updBookingBtnListener;
    private ActionListener customerViewBtnListener;
    private ActionListener roomViewBtnListener;
    private ActionListener serviceViewBtnListener;
    private ActionListener billViewBtnListener;
    private ActionListener logoutViewBtnListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RoomsTable;
    private javax.swing.JButton addBookingBtn;
    private javax.swing.JButton billViewBtn;
    private javax.swing.JButton bookingViewBtn;
    private javax.swing.JTable bookingsTB;
    private com.toedter.calendar.JDateChooser ckinDateTF;
    private com.toedter.calendar.JDateChooser ckoutDateTF;
    private javax.swing.JTextField cusIdTF;
    private javax.swing.JButton customerViewBtn;
    private javax.swing.JButton delBookingBtn;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutViewBtn;
    private javax.swing.JTextField roomIdTF;
    private javax.swing.JButton roomViewBtn;
    private javax.swing.JButton serviceViewBtn;
    private javax.swing.JButton updBookingBtn;
    // End of variables declaration//GEN-END:variables
}
