/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Customer;
import Controller.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.sql.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhattruong
 */
public class CustomerView extends javax.swing.JFrame {
   
    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
        frame = new JFrame("Customer Management");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   
    }

    public String getCusName() {
        return nameTF.getText();
    }
    
    public String getCusEmail() {
        return emailTF.getText();
    }

    public String getCusPhone() {
        return phoneTF.getText();
    }

    public String getCusAddress() {
        return addressTF.getText();
    }
    
    public String getCusId() {
        return idTF.getText();
    }
    
    public void setCusName(String name) {
        nameTF.setText(name);
    }
    
    public void setCusEmail(String email) {
        emailTF.setText(email);
    }

    public void setCusPhone(String phone) {
        phoneTF.setText(phone);
    }
    
    public void setCusAddress(String address) {
        addressTF.setText(address);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        customerViewBtn = new javax.swing.JButton();
        serviceViewBtn = new javax.swing.JButton();
        billViewBtn = new javax.swing.JButton();
        logoutViewBtn = new javax.swing.JButton();
        bookingViewBtn = new javax.swing.JButton();
        roomViewBtn = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        delCusBtn = new javax.swing.JButton();
        updCusBtn = new javax.swing.JButton();
        addCusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CusTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTF.setBorder(null);
        jPanel1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 333, 220, 30));

        emailTF.setBorder(null);
        jPanel1.add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 422, 220, 30));

        phoneTF.setBorder(null);
        jPanel1.add(phoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 512, 220, 30));

        addressTF.setBorder(null);
        jPanel1.add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 601, 220, 30));

        customerViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiImage/icon customer.png"))); // NOI18N
        customerViewBtn.setBorder(null);
        customerViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(customerViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 4, -1, 67));

        serviceViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiImage/icon service.png"))); // NOI18N
        serviceViewBtn.setBorder(null);
        serviceViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(serviceViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 4, -1, 67));

        billViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiImage/icon bill.png"))); // NOI18N
        billViewBtn.setBorder(null);
        billViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(billViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 4, -1, 67));

        logoutViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiImage/icon logout.png"))); // NOI18N
        logoutViewBtn.setBorder(null);
        logoutViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 4, -1, 67));

        bookingViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiImage/icon booking.png"))); // NOI18N
        bookingViewBtn.setBorder(null);
        bookingViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookingViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 4, -1, 67));

        roomViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiImage/icon room.png"))); // NOI18N
        roomViewBtn.setBorder(null);
        roomViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(roomViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 4, -1, 67));

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idLabel.setText("ID:");
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));
        jPanel1.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 120, -1));

        delCusBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delCusBtn.setForeground(new java.awt.Color(255, 51, 51));
        delCusBtn.setText("Delete");
        delCusBtn.setBorder(null);
        delCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCusBtnActionPerformed(evt);
            }
        });
        jPanel1.add(delCusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 671, 75, 20));

        updCusBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updCusBtn.setForeground(new java.awt.Color(255, 102, 0));
        updCusBtn.setText("Update");
        updCusBtn.setBorder(null);
        updCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updCusBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updCusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 671, 75, 20));

        addCusBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addCusBtn.setForeground(new java.awt.Color(0, 102, 51));
        addCusBtn.setText("Add");
        addCusBtn.setBorder(null);
        addCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addCusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 671, 55, 20));

        CusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Email", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(CusTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 500, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiImage/Customer.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String[][] dataTransfer(List<Customer> customers){
        int i =0 ;
        String data[][] = new String[customers.size()][5];
        for(Customer customer : customers){
            data[i][0] = String.valueOf(customer.getCusId());
            data[i][1] = customer.getCusName();
            data[i][2] = customer.getCusEmail();
            data[i][3] = customer.getCusPhone();
            data[i][4] = customer.getCusAddress();
            i++;
        }
        return data;
    }
    
    public void displayCustomers(List<Customer> customers) {
        String[][] data = dataTransfer(customers);
        String[] column = {"Customer ID", "Full Name", "Email", "Phone", "Address"};
        DefaultTableModel dataModel = new DefaultTableModel(data, column);
        CusTable.setModel(dataModel);
        frame.setVisible(true);
    }

    public void addCusBtnListener(ActionListener listener) {
        addCusBtn.addActionListener(listener);
    }
    public void delCusBtnListener(ActionListener listener) {
        delCusBtn.addActionListener(listener);
    }
    public void updCusBtnListener(ActionListener listener) {
        updCusBtn.addActionListener(listener);
    }
    public void bookingViewBtnListener(ActionListener listener) {
        bookingViewBtn.addActionListener(listener);
    }
    public void roomViewBtnListener(ActionListener listener) {
        roomViewBtn.addActionListener(listener);
    }
    public void serviceViewBtnListener(ActionListener listener) {
        serviceViewBtn.addActionListener(listener);
    }
    public void billViewBtnListener(ActionListener listener) {
       billViewBtn.addActionListener(listener);
    }
    public void logoutViewBtnListener(ActionListener listener) {
        logoutViewBtn.addActionListener(listener);
    }
    private void addCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusBtnActionPerformed
        if (addCusBtnListener != null) {
            addCusBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_addCusBtnActionPerformed

    private void delCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCusBtnActionPerformed
        if (delCusBtnListener != null) {
            delCusBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_delCusBtnActionPerformed

    private void updCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updCusBtnActionPerformed
        if (updCusBtnListener != null) {
            updCusBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_updCusBtnActionPerformed

    private void bookingViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingViewBtnActionPerformed
        if (bookingViewBtnListener != null) {
            bookingViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_bookingViewBtnActionPerformed

    private void roomViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomViewBtnActionPerformed
        if (roomViewBtnListener != null) {
            roomViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_roomViewBtnActionPerformed

    private void customerViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerViewBtnActionPerformed
    }//GEN-LAST:event_customerViewBtnActionPerformed

    private void serviceViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceViewBtnActionPerformed
        if (serviceViewBtnListener != null) {
            serviceViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_serviceViewBtnActionPerformed

    private void billViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billViewBtnActionPerformed
       if (billViewBtnListener != null) {
            billViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_billViewBtnActionPerformed

    private void logoutViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutViewBtnActionPerformed
        if (logoutViewBtnListener != null) {
            logoutViewBtnListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_logoutViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }
    private JFrame frame;
    private ActionListener addCusBtnListener;
    private ActionListener delCusBtnListener;
    private ActionListener updCusBtnListener;
    private ActionListener bookingViewBtnListener;
    private ActionListener roomViewBtnListener;
    private ActionListener serviceViewBtnListener;
    private ActionListener billViewBtnListener;
    private ActionListener logoutViewBtnListener;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CusTable;
    private javax.swing.JButton addCusBtn;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton billViewBtn;
    private javax.swing.JButton bookingViewBtn;
    private javax.swing.JButton customerViewBtn;
    private javax.swing.JButton delCusBtn;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutViewBtn;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton roomViewBtn;
    private javax.swing.JButton serviceViewBtn;
    private javax.swing.JButton updCusBtn;
    // End of variables declaration//GEN-END:variables

}
